# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

deploy:
  provider: script
  script: ls -la
  # Rscript deploy/deploy_shinyapps.R
  on:
    branch: master
